apiVersion: v1
kind: Service
metadata:
  name: armada-nginx-ingress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 4443
      protocol: TCP
      name: https
  selector:
    name: armada-nginx-ingress
    