apiVersion: apps/v1
kind: Deployment
metadata:
  name: armada-nginx-controller
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: armada-nginx-ingress
  template:
    metadata:
      labels:
        name: armada-nginx-ingress
    spec:
      containers:
        - name: armada-nginx-ingress-container
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0
          args:
            - /armada-nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/armada-nginx-configuration
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443