apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: armada-ingress-keycloak
  annotations:
    INGRESS.kubernetes.io/rewrite-target: /
spec: 
  rules:
  - host: login.armada.run
    http:
      paths:
      - path: /*
        backend:
          serviceName: keycloak
          servicePort: 8080